// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQIYK1VquzEpoGElOAHS-Vad_P_HYY1B8',
    appId: '1:326640343768:web:3053ff00d2a43a836115ad',
    messagingSenderId: '326640343768',
    projectId: 'chat-app-a60c7',
    authDomain: 'chat-app-a60c7.firebaseapp.com',
    storageBucket: 'chat-app-a60c7.appspot.com',
    measurementId: 'G-SWYYZZFS73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjgfIVsOEis5ddtlujF696kN7Vjxv0jz8',
    appId: '1:326640343768:android:058b14284687bfdf6115ad',
    messagingSenderId: '326640343768',
    projectId: 'chat-app-a60c7',
    storageBucket: 'chat-app-a60c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLH8gZGkCLt9TqyxSYvAPuXKyOo2NcP0s',
    appId: '1:326640343768:ios:475f839b85290ea96115ad',
    messagingSenderId: '326640343768',
    projectId: 'chat-app-a60c7',
    storageBucket: 'chat-app-a60c7.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
